language: clojure
before_script:
    - rm -Rf ~/.m2/repository/lein-doo
    - cd scripts; curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; cd ..
    - scripts/lein version
    - phantomjs -v
    - nvm use 0.12.7
    - node -v
script: scripts/lein tests
jdk:
    - oraclejdk8
sudo: required
dist: trusty
