language: clojure
before_script:
    - cd scripts; curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; cd ..
    - scripts/lein version
    - phantomjs -v
    - nvm install --lts
    - nvm use --lts
    - node -v
script: scripts/lein tests
jdk:
    - oraclejdk8
sudo: required
dist: trusty
